# References:
# https://gitlab.freedesktop.org/monado/monado
# https://aur.archlinux.org/packages/monado-git

name: Build Monado

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.7

    - name: Update packages and install git
      run: |
        pacman -Syyu --noconfirm
        pacman -S --noconfirm --needed git

    - name: Clone Monado repo
      run: |
        git clone --recursive https://gitlab.freedesktop.org/monado/monado.git

    - name: Get latest short commit hash
      id: get_commit
      run: |
        echo "commit=$(git --git-dir=OpenOVR/.git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Check if commit is already released
      id: check_release
      run: |
        latest_release=$(gh release view --json tagName --jq '.tagName' 2>/dev/null || echo "")
        if [[ "$latest_release" == "${{ env.commit }}" ]]; then
          echo "The latest release already matches the current commit (${latest_release})."
          echo "should_build=false" >> $GITHUB_ENV
        else
          echo "should_build=true" >> $GITHUB_ENV
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stop if no build is needed
      if: env.should_build == 'false'
      run: |
        echo "No changes since the last release. Exiting gracefully."
        exit 0

    - name: Install Monado dependencies
      run: |
        pacman -S --noconfirm --needed cmake python vulkan-headers glad eigen glslang libusb systemd-libs \
          v4l-utils libxcb ninja shaderc bluez-libs opencv cjson onnxruntime libjpeg-turbo libevent doxygen \
          hidapi graphviz zlib openmpi qt6-declarative qt6-base

    - name: Build Monado
      run: |
        cmake -B build -S monado
        cmake --build build

    - name: Find dynamic file
      id: find_file
      run: |
        libmonado_path=$(find build/src/xrt/targets/libmonado -name 'libmonado.so.*' | head -n 1)
        if [ -z "$libmonado_path" ]; then
          echo "File not found!"
          exit 1
        fi
        echo "libmonado_path=$libmonado_path" >> $GITHUB_ENV

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/src/xrt/targets/openxr/libopenxr_monado.so
          ${{ env.libmonado_path }}
        tag_name: ${{ env.commit }}
        name: Monado - ${{ env.commit }}
        body: |
          Automated build and release from commit: ${{ env.commit }}