# References:
# https://github.com/galister/wlx-overlay-s/wiki/Building-from-Source
# https://aur.archlinux.org/packages/wlx-overlay-s-git

name: Build wlx-overlay-s

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly build (every Sunday at midnight)

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
    - name: Update packages
      run: |
        pacman -Syyu --noconfirm

    - name: Install base dependencies
      run: |
        # Install base dependencies
        pacman -S --noconfirm git base-devel cmake libxkbcommon fontconfig dbus alsa-lib python3

        # Install rust
        pacman -S --noconfirm rust

    - name: Install wlx-overlay-s features dependencies
      run: |
        # openvr support
        pacman -S --noconfirm openvr

        # openxr support
        pacman -S --noconfirm openxr

        # wayland support
        pacman -S --noconfirm pipewire

        # x11 support
        pacman -S --noconfirm libx11 libxext libxrandr

        # pipewire support
        pacman -S --noconfirm libpipewire clang

        # wayvr support
        pacman -S --noconfirm wayland libglvnd

    - name: Clone repo and build wlx-overlay-s with all features
      run: |
        git clone https://github.com/galister/wlx-overlay-s.git
        cd wlx-overlay-s
        cargo build --release

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/release/wlx-overlay-s