# References:
# https://gitlab.com/znixian/OpenOVR
# https://aur.archlinux.org/packages/opencomposite-git

name: Build OpenComposite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.7

    - name: Update packages and install git
      run: |
        pacman -Syyu --noconfirm
        pacman -S --noconfirm --needed git

    - name: Clone OpenComposite repo
      run: |
        git clone --recursive https://gitlab.com/znixian/OpenOVR.git

    - name: Get latest short commit hash
      id: get_commit
      run: |
        echo "commit=$(git --git-dir=OpenOVR/.git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Check if commit is already released
      id: check_release
      run: |
        latest_release=$(gh release view --json tagName --jq '.tagName' 2>/dev/null || echo "")
        if [[ "$latest_release" == "${{ env.commit }}" ]]; then
          echo "The latest release already matches the current commit (${latest_release})."
          echo "should_build=false" >> $GITHUB_ENV
        else
          echo "should_build=true" >> $GITHUB_ENV
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stop if no build is needed
      if: env.should_build == 'false'
      run: |
        echo "No changes since the last release. Exiting gracefully."
        exit 0

    - name: Install OpenComposite dependencies
      run: |
        pacman -S --noconfirm --needed cmake make vulkan-headers libglvnd python

    - name: Build OpenComposite
      run: |
        cmake -B build -S OpenOVR
        cmake --build build

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/bin/linux64/vrclient.so
        tag_name: ${{ env.commit }}
        name: OpenComposite - ${{ env.commit }}
        body: |
          Automated build and release from commit: ${{ env.commit }}