# References:
# https://github.com/galister/wlx-overlay-s/wiki/Building-from-Source
# https://aur.archlinux.org/packages/wlx-overlay-s-git

name: Build wlx-overlay-s

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly build (every Sunday at midnight)

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.7

    - name: Update packages
      run: |
        pacman -Syyu --noconfirm

    - name: Install base dependencies
      run: |
        # Install base dependencies
        pacman -S --noconfirm git base-devel cmake libxkbcommon fontconfig dbus alsa-lib python3 libxkbcommon-x11

        # Install rust
        pacman -S --noconfirm rust

    - name: Install wlx-overlay-s features dependencies
      run: |
        # openvr support
        pacman -S --noconfirm openvr

        # openxr support
        pacman -S --noconfirm openxr

        # wayland support
        pacman -S --noconfirm pipewire

        # x11 support
        pacman -S --noconfirm libx11 libxext libxrandr

        # pipewire support
        pacman -S --noconfirm libpipewire clang

        # wayvr support
        pacman -S --noconfirm wayland libglvnd

    - name: Clone wlx-overlay-s repo
      run: |
        git clone https://github.com/galister/wlx-overlay-s.git

    - name: Get latest commit hash
      id: get_commit
      run: |
        echo "commit=$(git --git-dir=wlx-overlay-s/.git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Build wlx-overlay-s with all features
      run: |
        cargo build --release --manifest-path wlx-overlay-s/Cargo.toml

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          wlx-overlay-s/target/release/wlx-overlay-s
        tag_name: ${{ env.commit }}
        name: wlx-overlay-s - ${{ env.commit }}
        body: |
          Automated build and release from commit: ${{ env.commit }}