name: Build AUR Packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly build (every Sunday at midnight)

permissions:
  contents: write

jobs:
  build-packages:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
    - name: Update packages and install git
      run: |
        pacman -Syyu --noconfirm
        pacman -S --noconfirm --needed git
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Create non-root user
      run: |
        useradd -m -s /bin/bash builder
        echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

    - name: Install paru as non-root user
      run: |
        sudo -u builder bash -c '
          git clone https://aur.archlinux.org/paru-bin.git /home/builder/paru-bin
          makepkg -si --noconfirm --dir /home/builder/paru-bin
        '

    - name: Move Built Packages to /repo
      run: |
        mkdir -p repo

    - name: Commit and Push Repo
      run: |
        pwd
        ls -la .git
        cat .git/HEAD
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add repo
        git commit -a "Update AUR packages"
        git push
